server {
    listen 80;
    server_name the-bench.app www.the-bench.app;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name the-bench.app www.the-bench.app;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/the-bench.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/the-bench.app/privkey.pem;

    location / {
        try_files $uri /index.html;
    }
}