services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: thebench
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  mongo:
    image: mongo:latest
    container_name: mongo_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: thebench_news
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongo

volumes:
  pgdata:
  mongodata:
